name: Kernel Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install repo -y
          sudo git config --global user.name "root"
          sudo git config --global user.email "localhost"
          sudo timedatectl set-timezone Asia/Jakarta

      - name: Setup kernel source
        run: |
          repo init --repo-rev=v2.16 --depth=1 -u https://android.googlesource.com/kernel/manifest -b common-android12-5.10-lts
          repo sync -c --no-tags

      - name: Setup KernelSU
        run: |
          bash <(curl -Ls https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh)
          cat KernelSU/kernel/export_symbol.txt | awk '{sub("[ \t]+","");print "  "$0}' >> common/android/abi_gki_aarch64

      - name: Build images
        run: |
          wget -O common/build.config.gki https://raw.githubusercontent.com/JonesqPacMan/kernel-gki-build/main/build.config.gki
          sed -i 's/ -dirty//g' common/scripts/setlocalversion
          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
          echo "BUILD_TIME=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.BUILD_TIME }}
          path: out/android12-5.10/dist/boot.img
